### ISSUE TITLE
Support for mal-named artifacts

### ISSUE THREAD

**Issue by 0xlsca** [Wyn-Price/CurseForge-Maven-Helper#1]
I tried to use your tool, which already already potentially saved me hours of headaches, with this link

`
https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2616512
`

but it threw me a IOB Exception, which is no wonder because the artifact-name is not following the naming standard which other mod authors seem to follow. I for my part do not understand mentioned convention yet because of lacking documentation available (or own stupidity in regards of searching in the wrong spots for it), so I can't fix the issue on my own and create a PR.

So here's the question: Is there a way to support these mal-named artifact names?

**Comment by Wyn-Price** [comment]
Here's the thing, I don't actually know where that file is on the maven. I'll do some digging tonight and see if I can find it. My program however shouldn't throw an exception for abnormally named files. Could you post the full stacktrace (to get the stacktrace run the jar from the command line and put in the dodgy link)

**Comment by TomConnery** [comment]
Thanks for the reply,  I'm on my mobile right now but I can remember where the exception was thrown:

The 1st time the program ran through the method (mavenFromFile I think it was called) things went smoothly because the filename had a "-dev" suffix. The 2nd time, however, it crashed after the string ("Pam's Harvestcraft 1.12.2z") was split with "-" set as delimiter because the resulting array was accessed and my intuition tells me that at this point, the file name was expected to contain at least one "-" and thus a length of at least 2, which it did not have of course, hence the IOB Exception.

I'll get you the stacktrace in 3hrs, but you should be able to reproduce the Exception by simply using the link I provided (I think I did) or you could still visit the mod on CurseForge.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.09.2018, 08:47, Wyn Price <notifications@github.com> schrieb:
Here's the thing, I don't actually know where that file is on the maven. I'll do some digging tonight and see if I can find it. My program however shouldn't throw an exception for abnormally named files. Could you post the full stacktrace (to get the stacktrace run the jar from the command line and put in the dodgy link)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Wyn-Price/CurseForge-Maven-Helper","title":"Wyn-Price/CurseForge-Maven-Helper","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Wyn-Price/CurseForge-Maven-Helper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Wyn-Price in #1: Here's the thing, I don't actually know where that file is on the maven. I'll do some digging tonight and see if I can find it. My program however shouldn't throw an exception for abnormally named files. Could you post the full stacktrace (to get the stacktrace run the jar from the command line and put in the dodgy link)"}],"action":{"name":"View Issue","url":"https://github.com/Wyn-Price/CurseForge-Maven-Helper/issues/1#issuecomment-425338875"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Wyn-Price/CurseForge-Maven-Helper/issues/1#issuecomment-425338875",
"url": "https://github.com/Wyn-Price/CurseForge-Maven-Helper/issues/1#issuecomment-425338875",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Wyn-Price/CurseForge-Maven-Helper] Support for mal-named artifacts (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Wyn Price**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Wyn-Price",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Wyn-Price/CurseForge-Maven-Helper\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Wyn-Price/CurseForge-Maven-Helper\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Wyn-Price/CurseForge-Maven-Helper/issues/1#issuecomment-425338875"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385272915\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by TomConnery** [comment]
Here's the stacktrace, as promised (1st three lines are a representation of the splitArtifact array):

```
[Pam's HarvestCraft 1.12.2z, dev]
[Pam's HarvestCraft 1.12.2z, dev, ]
[Pam's HarvestCraft 1.12.2z]
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.wynprice.curseforgemaven.Main.getMavenValues(Main.java:227)
	at com.wynprice.curseforgemaven.Main.calculate(Main.java:147)
	at com.wynprice.curseforgemaven.Main.lambda$run$0(Main.java:69)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Wyn-Price** [comment]
I have time today to work on this. Ill see if i can figure out how curseforge handles it themselves

**Comment by Wyn-Price** [comment]
Looked into it. The issue is from https://github.com/Wyn-Price/CurseForge-Maven-Helper/blob/a7a16edb2b0af97c2396dbfc5c0bafb65461e22c/src/main/java/com/wynprice/curseforgemaven/Main.java#L222. I'm assuming that the file name has at least one `-` in it. Ill look into how curseforge figures (if it even does) this out. All of the rest of the calculations require at least one `-`, so ill probably just add a special case

**Comment by Trinsdar** [comment]
I seem to have a similar issue with ic2 classic: https://minecraft.curseforge.com/projects/ic2-classic/files/2644075
I used this, which is what it spit out: deobfCompile "ic2-classic:IC2Classic 1.12:1.5.4.0 Dev"
and I got this error:
`> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve ic2-classic:IC2Classic 1.12:1.5.4.0 Dev.
     Required by:
         com.rumaruka.emt:Industrial-Magic---Crossover:R_EMT10.5
      > Could not resolve ic2-classic:IC2Classic 1.12:1.5.4.0 Dev.
         > Could not get resource 'https://minecraft.curseforge.com/api/maven/ic2-classic/IC2Classic%201.12/1.5.4.0%20Dev/IC2Classic%201.12-1.5.4.0%20Dev.jar'.
            > Could not HEAD 'https://minecraft.curseforge.com/api/maven/ic2-classic/IC2Classic%201.12/1.5.4.0%20Dev/IC2Classic%201.12-1.5.4.0%20Dev.jar'.
               > org.apache.http.client.ClientProtocolException (no error message)`
this is the stacktrace: https://paste.dimdev.org/esufacenos.cs

**Comment by TagnumElite** [comment]
I don't know if this information will help but when using the tool on [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2663947) it will come out with `deobfCompile "nuclearcraft-mod:NuclearCraft-2.13e::1.12.2"` which is wrong.

Using the [sources](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2663949) with the tool however results in `
deobfCompile "nuclearcraft-mod:NuclearCraft-2.13e-:1.12.2:sources"` which is correct.
